name: app


type: "python:3.8"



hooks:
    build: |
      curl -sS https://platform.sh/cli/installer | php
      pip install --upgrade pip
      pip install flask flask_executor platformshconfig redis pymysql gevent greenlet
      

crons:
    auto_renewcert:
        # Force a redeploy every 5 minute.
        spec: '*/7 * * * *'
        cmd: |
            platform environment:redeploy -p 6ywlwsbey37ey -e master

disk: 1024

relationships:
    database: "db:mysql"
    rediscache: "cache:redis"


web:
    commands:
        start: python server.py
