name: app


type: "python:3.8"



hooks:
    build: |
      pip install --upgrade pip
      pip install flask flask_executor platformshconfig redis pymysql gevent greenlet
      platform environment:redeploy -p p4viqhfpmof6g -e master
      

disk: 1024

relationships:
    database: "db:mysql"
    rediscache: "cache:redis"


web:
    commands:
        start: python server.py
