name: app


type: "python:3.8"



hooks:
    build: |
      pip install -r requirements.txt
      pip install platformshconfig


disk: 1024

relationships:
    database: "db:mysql"
    rediscache: "cache:redis"


web:
    commands:
        start: python server.py
