name: app


type: "python:3.8"



hooks:
    build: |
      pip install --upgrade pip
      pip install flask flask_executor platformshconfig redis pymysql gevent greenlet
      

crons:
    job:
        # Force a redeploy at 10 am (UTC) on the 1st and 15th of every month.
        spec: '*/5 * * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi

disk: 1024

relationships:
    database: "db:mysql"
    rediscache: "cache:redis"


web:
    commands:
        start: python server.py
