name: app


type: "python:3.8"



hooks:
    build: |
      curl -sS https://platform.sh/cli/installer | php
      pip install --upgrade pip
      pip install flask flask_executor platformshconfig redis pymysql gevent greenlet
      

crons:
    job:
        # Force a redeploy every five minute
        spec: '*/5 * * * *'
        cmd: |
            platform environment:redeploy -p  -e master

disk: 1024

relationships:
    database: "db:mysql"
    rediscache: "cache:redis"


web:
    commands:
        start: python server.py
