name: app


type: "python:2.7"


dependencies:
    python:
        pipenv: "2018.10.13"


hooks:
    build: |
      pipenv install --system --deploy


disk: 1024

relationships:
    database: "db:mysql"
    rediscache: "cache:redis"


web:
    commands:
        start: python server.py
